# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Timer.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(520, 423)
        self.counter_label = QtWidgets.QLabel(Form)
        self.counter_label.setGeometry(QtCore.QRect(120, 30, 271, 61))
        self.counter_label.setObjectName("counter_label")
        self.Start_button = QtWidgets.QPushButton(Form)
        self.Start_button.setGeometry(QtCore.QRect(30, 220, 121, 41))
        self.Start_button.setObjectName("Start_button")
        self.End_button = QtWidgets.QPushButton(Form)
        self.End_button.setGeometry(QtCore.QRect(370, 220, 121, 41))
        self.End_button.setObjectName("End_button")
        self.second = QtWidgets.QLabel(Form)
        self.second.setGeometry(QtCore.QRect(320, 130, 58, 61))
        self.second.setObjectName("second")
        self.minute = QtWidgets.QLabel(Form)
        self.minute.setGeometry(QtCore.QRect(220, 130, 58, 61))
        self.minute.setObjectName("minute")
        self.hour = QtWidgets.QLabel(Form)
        self.hour.setGeometry(QtCore.QRect(130, 130, 58, 61))
        self.hour.setObjectName("hour")
        self.just_set_here = QtWidgets.QLabel(Form)
        self.just_set_here.setGeometry(QtCore.QRect(190, 120, 21, 71))
        self.just_set_here.setObjectName("just_set_here")
        self.just_set_here_2 = QtWidgets.QLabel(Form)
        self.just_set_here_2.setGeometry(QtCore.QRect(290, 120, 21, 71))
        self.just_set_here_2.setObjectName("just_set_here_2")
        self.tmp_button = QtWidgets.QPushButton(Form)
        self.tmp_button.setGeometry(QtCore.QRect(200, 220, 121, 41))
        self.tmp_button.setObjectName("tmp_button")
        self.inputHourBox = QtWidgets.QLineEdit(Form)
        self.inputHourBox.setGeometry(QtCore.QRect(100, 290, 113, 31))
        self.inputHourBox.setObjectName("inputHourBox")
        self.hourLabel = QtWidgets.QLabel(Form)
        self.hourLabel.setGeometry(QtCore.QRect(30, 290, 71, 41))
        self.hourLabel.setObjectName("hourLabel")
        self.minuteLabel = QtWidgets.QLabel(Form)
        self.minuteLabel.setGeometry(QtCore.QRect(30, 330, 71, 41))
        self.minuteLabel.setObjectName("minuteLabel")
        self.inputMinuteBox = QtWidgets.QLineEdit(Form)
        self.inputMinuteBox.setGeometry(QtCore.QRect(100, 330, 113, 31))
        self.inputMinuteBox.setObjectName("inputMinuteBox")
        self.secondLabel = QtWidgets.QLabel(Form)
        self.secondLabel.setGeometry(QtCore.QRect(30, 370, 71, 41))
        self.secondLabel.setObjectName("secondLabel")
        self.inputSecondBox = QtWidgets.QLineEdit(Form)
        self.inputSecondBox.setGeometry(QtCore.QRect(100, 370, 113, 31))
        self.inputSecondBox.setObjectName("inputSecondBox")
        self.setTimeButton = QtWidgets.QPushButton(Form)
        self.setTimeButton.setGeometry(QtCore.QRect(220, 360, 121, 41))
        self.setTimeButton.setObjectName("setTimeButton")
        self.playMusicButton = QtWidgets.QPushButton(Form)
        self.playMusicButton.setGeometry(QtCore.QRect(370, 360, 121, 41))
        self.playMusicButton.setObjectName("playMusicButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.counter_label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:26pt; font-weight:600;\">倒數計時器</span></p></body></html>"))
        self.Start_button.setText(_translate("Form", "Start"))
        self.End_button.setText(_translate("Form", "End"))
        self.second.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:26pt;\">00</span></p></body></html>"))
        self.minute.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:26pt;\">00</span></p></body></html>"))
        self.hour.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:26pt;\">00</span></p></body></html>"))
        self.just_set_here.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:26pt;\">:</span></p></body></html>"))
        self.just_set_here_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:26pt;\">:</span></p></body></html>"))
        self.tmp_button.setText(_translate("Form", "Stop/Continue"))
        self.hourLabel.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Hour</span></p></body></html>"))
        self.minuteLabel.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Minute</span></p></body></html>"))
        self.secondLabel.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Second</span></p></body></html>"))
        self.setTimeButton.setText(_translate("Form", "setTime"))
        self.playMusicButton.setText(_translate("Form", "playMusic"))
